<?php

/**
 * @file
 * Module file for github_repo_users_module.
 */

/**
 * Implements hook_menu().
 *
 * @see hook_menu()
 */
function github_repo_users_menu() {

  // This is the minimum information you can provide for a menu item. This menu
  // item will be created in the default menu, usually Navigation.
  $items['drupalconsole-contributors'] = array(
    'title' => 'DrupalConsole Contributors',
    'page callback' => 'github_repo_users_page',
    'access callback' => TRUE,
    //'expanded' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Constructs a descriptive page.
 *
 * Our menu maps this function to the path 'examples/page_example'.
 */
function github_repo_users_page() {

  // Get cURL resource
  $curl = curl_init();
  // Set some options - we are passing in a useragent too here
  curl_setopt_array($curl, array(
      CURLOPT_RETURNTRANSFER => 1,
      CURLOPT_URL => 'https://api.github.com/repos/hechoendrupal/DrupalConsole/contributors',
      CURLOPT_USERAGENT => 'Drupal 7'
  ));


  // Send the request & save response to $resp
  $resp = json_decode(curl_exec($curl));


  // Close request to clear up some resources
  curl_close($curl);


  if ( is_array($resp) && count($resp) > 0 ){
    $output = '';
    foreach ($resp as $item => $value){
      $output .= '<div style="width:200px;padding:10px;float:left;text-align:center;">';
      $output .= '<a href="'.$value->html_url.'" target="_blank">';
      $output .= '<img style="width:150px;border-radius:75px;display:block;margin:0 auto;" alt="Avatar" src="'.$value->avatar_url.'" /><h3 style="display:block;text-align:center">'.$value->login.'</h3></td></tr>';
      $output .= '</a>';
      $output .= '</div>';
    }

  }

  return array(
    '#markup' => $output
  );

}
